# Generated by Django 5.1.6 on 2025-03-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
