# Generated by Django 5.1.6 on 2025-02-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_image_2_sale_image_3_alter_sale_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
